### PR TITLE
Markdown lint-induced clean-up of doc files.

### PR DESCRIPTION
**Pull request by PawelWMS**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

A small clean-up of two doc files to follow [Markdown lint's guidelines](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md) to have a higher chance of the pages being displayed properly on all browsers and other tools capable of interpreting .md files.

Most of the changes are added/removed whitespaces. There are also a few single fixes (see: change log below).

###### Change Log  

- Added/removed spacing and empty lines according to [Markdown lint's guidelines](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md).
- Fixed one bash section with a quadruple back quote - made a bash comment be interpreted as a header in VS Code's viewer.
- Prevented template URLs containing `$(VARIABLE)` entries from being turned into broken hyperlinks.
- Changed two `NOTE:` lines from being a header to bold text, so they don't appear in the table of contents.
- Decreased header level of `All Build Variables` so it's not interpreted as a subsection of `Reproducing a Build`.

###### Does this affect the toolchain?  

No

###### Test Methodology

- Viewed the updated doc in Edge, Firefox and a viewer from VS Code's MD plug-in.

### CODE REVIEW

**Comment by dmcilvaney** [comment]
Is this a test we could/should automate for PRs? Make sure the docs stay well formatted... We already do something similar for the Go files.

**Review by dmcilvaney — APPROVED** [review]

**Comment by PawelWMS** [comment]
This is a very good question and I'd love to have that automated step. I strongly believe we should have a check for proper formatting of our docs and I simply didn't have the time to find and apply any such tooling at the moment. I've just created an [issue on GitHub](https://github.com/microsoft/CBL-Mariner/issues/126) so we at least don't lose it.

---
In reply to: [696216944](https://github.com/microsoft/CBL-Mariner/pull/122#issuecomment-696216944) [](ancestors = 696216944)

**Comment by lpereira** [comment]
A lot of these things can be automated with @msftbot. I can show some of the things it can do in a call this week if people is interested.

**Comment by PawelWMS** [comment]
@lpereira: I'd certainly love to learn more what the bot can do for us here. If there's not going to be enough time during that weekly call, I'll reach out to you separately, if you don't mind.

**Pull request merged**
