### PR TITLE
python-jsonschema: Upgrade to 4.4.0

### PR DESCRIPTION
**Pull request by oliviacrain**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Upgrade `python-jsonschema` to the latest upstream version. As a consequence, we promote `python-pyrsistent` to core (while also bumping its version to latest).

###### Change Log  

- `python-jsonschema`: version bump 2.6.0 -> 4.4.0
- `python-jsonschema`: Use tox to run tests
- `python-pyrsistent`: version bump 0.17.3 ->  0.18.1
- `python-pyrsistent`: Use tox to run tests and pull test dependencies from PyPI
- `python-pyrsistent`: Promoted to Mariner Core
- `python-pyrsistent`: License verified
- `python-pyrsistent`: Lint spec

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Local check/non-check builds pass

### CODE REVIEW

**Review by jslobodzian — CHANGES_REQUESTED** [review]
Does this fix a CVE?  If not, this is blocked until post GA

**Comment by oliviacrain** [comment]
@jslobodzian I believe this is one of the upgrades that you brought up as an exemption to the block- unless something has changed since last Friday.

**Review by mfrw — APPROVED** [review]
LGTM.
PS: I had upgraded `jsonschema` this a few weeks back and had to revert as it broke the build somewhere down the line. Lets tread with caution :)

**Comment by nisamson** [comment]
Olivia, looks like this might have gotten lost in the fracas

**Pull request closed without merging**
