### PR TITLE
redis: Update from 6.2.13 to 7.2.4 in Mariner 3.0

### PR DESCRIPTION
**Pull request by sharath-srikanth-chellappa**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

The PR is the upgrade of redis package in Mariner 3.0 from version 6.2.13 to 7.2.4

###### Change Log  

- Bump version to 7.2.4 for Mariner 3.0
- Remove the Patch File for redis and give an explanation in the file as to why its removed.
- Change signatures.json and cgmanifest.json to show the updated hash and versions for the package.

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Pipeline Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489235&view=results

### CODE REVIEW

**Review by neha170 — COMMENTED** [review]
I see v7.2.4 released on Jan 9. Can we try to upgrade to that, thanks

**Comment by reubeno** [comment]
It would also be helpful if you could explain the reasoning behind patch removal for reviewers (like me :)) not specifically familiar with this package. (e.g., Is the patch now upstreamed? Is it no longer required? Are we intentionally choosing to discard azlinux-specific  customization?)

**Review by anphel31 — APPROVED** [review]

**Comment by sharath-srikanth-chellappa** [comment]
Converting to a draft since we want to upgrade to 7.2.4 after the release on Jan 9. Will republish once the changes are made

**Comment by sharath-srikanth-chellappa** [comment]
@neha170 I have gone ahead and updated to 7.2.4 as requested.

@reubeno I have gone ahead and updated the reason why the SPECS/redis/disable_active_defrag_big_keys.patch has been removed. I have readded the redis-conf.patch since the 7.2.4 version does not have the changes that is given in that patch.

**Review by neha170 — APPROVED** [review]

**Pull request merged**
