### PR TITLE
Add multus v3.8 rpm

### PR DESCRIPTION
**Pull request by yapancha**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Add multus-cni rpm to mariner.
These are needed by ECF undercloud (bare metal)

###### Change Log  

- Spec file imported from openSUSE and modified to build for mariner.

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Installed the built rpms on a mariner system

### CODE REVIEW

**Review by mfrw — APPROVED** [review]
LGTM :)

**Comment by yapancha** [comment]
@mfrw I don't see option to merge.

**Comment by mfrw** [comment]
> @mfrw I don't see an option to merge.

You are not a part of [cbl-mariner-devs](https://github.com/orgs/microsoft/teams/cbl-mariner-devs). Please raise a request :)
Push/Merge rights are restricted to folks that belong to the said team.

**Review by kanikanema — APPROVED** [review]
LGTM

**Comment by yapancha** [comment]
Thanks for merging @mfrw I have also requested to join [cbl-mariner-devs](https://github.com/orgs/microsoft/teams/cbl-mariner-devs).

**Pull request merged**
