### PR TITLE
glog: Add package version 0.3.5

### PR DESCRIPTION
**Pull request by suresh-thelkar**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Add package glog v0.3.5

###### Change Log  
- Add package

###### Does this affect the toolchain?  
**NO**

###### Associated issues  
- NA

###### Links to CVEs  
- NA

###### Test Methodology
- Local Build with RUN_CHECK=y

BuddyBuild:
- AMD64: [PR-4171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=261463&view=results)
- ARM64: [PR-4171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=261470&view=results)

BuddyBuild After fixing Spec Linter warnings:
- AMD64: [PR-4171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=262348&view=results)
- ARM64: [PR-4171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=262350&view=results)

### CODE REVIEW

**Review by Camelron — APPROVED** [review]
looks good to me

**Comment by PawelWMS** [comment]
@suresh-thelkar, from the title it looks like this is still a draft, so I converted it to one for you - this is our common way of letting people know, that this is still work in progress and doesn't need to be reviewed, yet.

**Comment by suresh-thelkar** [comment]
> looks good to me

Thank you for the review and sign off

**Review by mfrw — APPROVED** [review]
LGTM :)
Welcome to Mariner 🥇

**Comment by suresh-thelkar** [comment]
> LGTM :) Welcome to Mariner 🥇

Thank you.

**Pull request merged**
