### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by slowy07**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

fetch from ``1..0 dev`` and create custom branch to fix typo spelling grammar, with reference from [merriam webster](merriam-webster.com)

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES**

###### Associated issues  

- #1292 

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

### CODE REVIEW

**Comment by slowy07** [comment]
closed because conflicts

**Review by slowy07 — COMMENTED** [review]
fix conflicts from branch ``1.0-dev`` and merget into ``minor-changes``

**Review by PawelWMS — CHANGES_REQUESTED** [review]
Blocking until we get the branch gets cleaned-up (no commits from other authors).

**Comment by slowy07** [comment]
closed cause commit from other contributors

**Pull request closed without merging**
