### PR TITLE
Add support to systemd-resolved to serve stale dns data

### PR DESCRIPTION
**Pull request by prmis**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Systemd-resolved exposes the following varlink methods that can be used to extract crucial metrics or counters, providing useful insights into the system's DNS operations. OSS PR#28327

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: [[PR-5945](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=409409)]

Tested with below commands
sudo ./resolvectl show-server-state --json=pertty
sudo ./resolvectl statistics
sudo ./resolvectl reset-statistics

### CODE REVIEW

**Comment by ddstreetmicrosoft** [comment]
@prmis this doesn't build, did you backport the patch (including other patches needed for the code changes)?

**Comment by prmis** [comment]
Due to other high-priority commitments this week, I am unable to immediately backport the changes another dependency PR #28012 related to the JSON modifications. It appears to be a significant change.

Given this, I propose that we proceed to with the release/ patching of systemd without incorporating this monitoring feature. I will work  on the backporting process and aim to submit a PR within the next 1 to 2 weeks.

@Dan ***@***.***>, is it OK?

Thanks
Pradeep


Sent from mobile please excuse brevity

________________________________

**Comment by ddstreetmicrosoft** [comment]
That works for me, the other 2 patches are already in the latest released mariner systemd package.

________________________________________

**Comment by prmis** [comment]
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=409409&view=results with latest PR changes

**Comment by prmis** [comment]
@ddstreetmicrosoft, please review

**Comment by ddstreetmicrosoft** [comment]
Please keep the upstream patch file(s) unmodified, or at least minimally modified. We cannot accept a huge single patch file with no clear connection to all its upstream commits.

**Review by ddstreetmicrosoft — CHANGES_REQUESTED** [review]
Needs significant changes; upstream commits must be provided as separate patch files with minimal modification (only for minor context changes). Any significant non-upstream changes need to be in a separate patch file with clear documentation as to the need and intent

**Comment by prmis** [comment]
Ok, I will create two seperate Patch file and add 2 patch file 1.jason format chnages 2.statics.

**Comment by ddstreetmicrosoft** [comment]
I discussed with @prmis and we agreed it's better to close this for mariner 2, and wait until mariner 3 for this functionality, as the updated systemd in mariner 3 will contain this without any need for backporting.

**Pull request closed without merging**
