### PR TITLE
Remove default CONFIG_FILE=

### PR DESCRIPTION
**Pull request by dmcilvaney**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

**This will remove the default value `CONFIG_FILE=./imageconfigs/core-efi.json` and replcae it with `CONFIG_FILE=""**

One of the most common sources of frustration for users of the toolkit is the default selection of the `core-efi.json` config file. This would cause pointless package rebuilds since even `sudo make build-packages` would be configured to create all the packages needed to build the image (including the kernel which is quite slow).

###### Change Log  

- Make the default value for `CONFIG_FILE` be `""`

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Local builds

### CODE REVIEW

**Review by neha170 — COMMENTED** [review]
Just fyi, it's directed towards 2.0 instead of main

**Comment by dmcilvaney** [comment]
> Just fyi, it's directed towards 2.0 instead of main

Thanks, fixed

**Review by christopherco — COMMENTED** [review]
> One of the most common sources of frustration for users of the toolkit is the default selection of the core-efi.json config file. This would cause pointless package rebuilds since even sudo make build-packages would be configured to create all the packages needed to build the image (including the kernel which is quite slow).

From reading the description, I understand the rationale behind changing the default selection away from `CONFIG_FILE=core-efi.json` by default, since the main complaint we've had is this default value subverts the general expectations of running `make build-packages` to build all packages. So the intent here is to make the new default behavior build all possible packages, unless additional arguments are provided to confine the package build list?

Curious, how does `CONFIG_FILE=""` subvert the package rebuild issue? I thought we had SPEC directory file change tracking to prevent pointless package rebuilds, independent of `CONFIG_FILE=`'s value? So for the `build packages` part of the tooling, `CONFIG_FILE=` would simply inform what packages are desired to have available. And `CONFIG_FILE=""` meant all packages should be available. Is this no longer the case, or am I missing certain parts of how `build-packages` works?

**Comment by dmcilvaney** [comment]
> > One of the most common sources of frustration for users of the toolkit is the default selection of the core-efi.json config file. This would cause pointless package rebuilds since even sudo make build-packages would be configured to create all the packages needed to build the image (including the kernel which is quite slow).
> 
> From reading the description, I understand the rationale behind changing the default selection away from `CONFIG_FILE=core-efi.json` by default, since the main complaint we've had is this default value subverts the general expectations of running `make build-packages` to build all packages. So the intent here is to make the new default behavior build all possible packages, unless additional arguments are provided to confine the package build list?
> 
> Curious, how does `CONFIG_FILE=""` subvert the package rebuild issue? I thought we had SPEC directory file change tracking to prevent pointless package rebuilds, independent of `CONFIG_FILE=`'s value? So for the `build packages` part of the tooling, `CONFIG_FILE=` would simply inform what packages are desired to have available. And `CONFIG_FILE=""` meant all packages should be available. Is this no longer the case, or am I missing certain parts of how `build-packages` works?

No, you have a good understanding of the underlying flow. The actual impact to the user though, is much more outsized. Even if they are working on a single package, if that package is very low down in the graph the scheduler will cascade the rebuilds up through the graph. A simple release bump in a foundational package that should take 5 minutes to build can result in a build that takes hours. This is partly remediated by https://github.com/microsoft/CBL-Mariner/pull/5993 however that feature is currently not on by default.

**Review by christopherco — APPROVED** [review]

**Comment by christopherco** [comment]
> > > One of the most common sources of frustration for users of the toolkit is the default selection of the core-efi.json config file. This would cause pointless package rebuilds since even sudo make build-packages would be configured to create all the packages needed to build the image (including the kernel which is quite slow).
> > 
> > 
> > From reading the description, I understand the rationale behind changing the default selection away from `CONFIG_FILE=core-efi.json` by default, since the main complaint we've had is this default value subverts the general expectations of running `make build-packages` to build all packages. So the intent here is to make the new default behavior build all possible packages, unless additional arguments are provided to confine the package build list?
> > Curious, how does `CONFIG_FILE=""` subvert the package rebuild issue? I thought we had SPEC directory file change tracking to prevent pointless package rebuilds, independent of `CONFIG_FILE=`'s value? So for the `build packages` part of the tooling, `CONFIG_FILE=` would simply inform what packages are desired to have available. And `CONFIG_FILE=""` meant all packages should be available. Is this no longer the case, or am I missing certain parts of how `build-packages` works?
> 
> No, you have a good understanding of the underlying flow. The actual impact to the user though, is much more outsized. Even if they are working on a single package, if that package is very low down in the graph the scheduler will cascade the rebuilds up through the graph. A simple release bump in a foundational package that should take 5 minutes to build can result in a build that takes hours. This is partly remediated by #5993 however that feature is currently not on by default.

Thanks for the explanation @dmcilvaney. I recommend adding a bit more information to the PR description and final squash merge message that clearly highlights the removal of `CONFIG_FILE=core-efi.json` default is changed to `CONFIG_FILE=""` which defaults to considering all packages wherever `CONFIG_FILE=` is passed, which IIRC is pretty much every top-level go application.

**Pull request merged**
