### PR TITLE
Promote bluez, libicall, and libell to base repo

### PR DESCRIPTION
**Pull request by dallasd1**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Move packages bluez, libical, and libell from SPECS-EXTENDED to SPECS folder.

###### Change Log  

- Moved directories to the SPECS folder
- Bump release number

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Test Methodology

- Local build

### CODE REVIEW

**Review by PawelWMS — CHANGES_REQUESTED** [review]
[Similar comments](https://github.com/microsoft/CBL-Mariner/pull/3374#pullrequestreview-1039308590) as for #3374:

Specs from `SPECS-EXTENDED` rarely can be simply moved into `SPECS` without additional work as they have a lower bar in terms of test, spec structure, linting, etc.

Please make sure to now:
- Lint the spec.
- Make sure the ptests (inside the `%check` section) run successfully.
- Remove all references to other distros (if any). In most cases we tend to keep the parts of the spec, which were enabled for Fedora and remove the other ones.
- Remove the GPG keyring and signatures - we rely on the `signatures.json` files.
- Make sure all automated PR checks pass (hard to miss, you probably won't be able to merge before the required ones are resolved).

**Comment by PawelWMS** [comment]
Please close #3377, if you've switched to this PR.

**Comment by dallasd1** [comment]
The specs were linted with rpmlint, excluding warnings and error "lib-package-without-%mklibname". I see the same log in other spec files so please let me know if it's still an issue. Please let me know if there is other documentation on completing the checklist if I'm missing anything.

**Comment by PawelWMS** [comment]
> The specs were linted with rpmlint, excluding warnings and error "lib-package-without-%mklibname". I see the same log in other spec files so please let me know if it's still an issue. Please let me know if there is other documentation on completing the checklist if I'm missing anything.

Ah, I should have mentioned more details about linting the spec. [Here's more details](https://dev.azure.com/mariner-org/mariner/_wiki/wikis/mariner.wiki/125/Introduction-to-SPEC-Files?anchor=spec-linter) about how to configure the one we're using (just 3 short steps). That's also what the "Spec Linting" PR check is running. The linter might change a few things in the wrong way (that's why the PR check is not required btw.) but in general it's reliable and I'll help you out with anything that the linter might get wrong. We're still tweaking it a bit.

**Comment by dallasd1** [comment]
> > The specs were linted with rpmlint, excluding warnings and error "lib-package-without-%mklibname". I see the same log in other spec files so please let me know if it's still an issue. Please let me know if there is other documentation on completing the checklist if I'm missing anything.
> 
> Ah, I should have mentioned more details about linting the spec. [Here's more details](https://dev.azure.com/mariner-org/mariner/_wiki/wikis/mariner.wiki/125/Introduction-to-SPEC-Files?anchor=spec-linter) about how to configure the one we're using (just 3 short steps). That's also what the "Spec Linting" PR check is running. The linter might change a few things in the wrong way (that's why the PR check is not required btw.) but in general it's reliable and I'll help you out with anything that the linter might get wrong. We're still tweaking it a bit.

Thanks for the info and pointing me to the document! The specs have now been linted using the spec-cleaner

**Review by PawelWMS — APPROVED** [review]

**Pull request merged**
