### PR TITLE
Fix package toolchain list

### PR DESCRIPTION
**Pull request by AZaugg**
When downloading the toolchain used to build mariner, a few packages are missing in the upstream repo:
https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64

Updating the version information so toolchain build can succeed fixes #32

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Comment by dmcilvaney** [comment]
Its expected the `main` branch may be behind the published packages in PMC. There are a few ways I recommend working around:
- Build from sources (`REBUILD_TOOLCHAIN=y`). You can save the produced archive aside and reference it using `TOOLCHAIN_ARCHIVE=my_toolchain.tar.gz`
- Dev off of the rolling `2.0-stable` branch (won't have the bleeding edge stuff)
- `git checkout 2.0-stable -- toolkit/resources/manifests/package` This will just roll the manifests back

**Comment by dmcilvaney** [comment]
We wrote up some bits on our branches here: https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/building/building.md#clone-and-sync-to-stable-commit 

Not sure if this is something you have run into, took me by surprise. Git behaves oddly (at least feels odd to me) with tags, you need to explicitly ask it to pull updates to tags via `git fetch upstream --tags`. It won't update the rolling tags once you have one defined locally on its own.

**Review by PawelWMS — CHANGES_REQUESTED** [review]
This seems incorrect, but I see Daniel has already provided explanations. I'm just blocking it, so we don't accidentally get this merged.

**Comment by AZaugg** [comment]
Ahh, apologies, I was not aware of the 2.0-stable branch, let me close this out

**Pull request closed without merging**
