### PR TITLE
Upgrade Blobfuse2 to 2.0.4

### PR DESCRIPTION
**Pull request by souravgupta-msft**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Upgrade Blobfuse2 to latest version

###### Change Log  

- Upgrade Blobfuse2 to latest version

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Review by mfrw — COMMENTED** [review]
Can you please channge the target branch to `main` instead of `2.0`

**Review by mfrw — CHANGES_REQUESTED** [review]
Something does not look right here.
35 commits seems too much.
Would you please take a look again, I think, we would only need one commit [this](https://github.com/microsoft/CBL-Mariner/pull/5838/commits/c9b2941ecdc015d521bffc88d18912e751d6e589).

**Comment by souravgupta-msft** [comment]
> Something does not look right here. 35 commits seems too much. Would you please take a look again, I think, we would only need one commit [this](https://github.com/microsoft/CBL-Mariner/pull/5838/commits/c9b2941ecdc015d521bffc88d18912e751d6e589).

This is because I created my branch from the `2.0` branch. So, when I changed the target branch to `main`, the commits from the `2.0` branch also came in. I will create a new PR with just the blobfuse2 commit.

**Comment by souravgupta-msft** [comment]
@mfrw, can you pelase review the PR, #5839.

**Pull request closed without merging**
