### PR TITLE
Use the PIC'ed version of libiberty.a static object

### PR DESCRIPTION
**Pull request by AZaugg**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

Use the PIC versioned static object instead of the non -fPIC

###### Change Log  

- Use the PIC'ed version of libiberty.a static object

###### Does this affect the toolchain?  

**YES**

###### Test Methodology

- Build out binutills-devel
- Exploded RPM
- Checked library
```
azaugg@azaugg-ld77 [ /tmp/b/usr/lib ]$ readelf --relocs libiberty.a | grep 'R_X86_64_PLT32'
0000000001e7  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
00000000027c  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
0000000003db  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
```

### CODE REVIEW

**Review by mfrw — COMMENTED** [review]
`binutils` does affect the `Toolchain` :)
We might want to modify the `toolkit/manifest` files as well :)

**Comment by AZaugg** [comment]
> `binutils` does affect the `Toolchain` :) We might want to modify the `toolkit/manifest` files as well :)

Done, corrected. Apologies, missed it

**Review by mfrw — APPROVED** [review]
Change Looks good to me.
I would request a full build though :) before a merge.
/cc @anphel31

**Review by mfrw — COMMENTED** [review]
Had triggered a "FULL-BUILD" w/ this change.
Toolchain built fine & ARM everything built fine but Build-RPMS for AMD was unhappy for `javapackages-bootstrap`.

This seems unrelated to this specific change, but none-the-less we do not have a clean full build.

Pipeline Link: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418599&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667&l=28003)

**Review by christopherco — APPROVED** [review]

**Review by mfrw — COMMENTED** [review]
Retriggered a new Full Build: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=420517&view=results)

**Review by ddstreetmicrosoft — APPROVED** [review]
This looks fine. The other static libs will need the same handling, too, though I'm not sure we should make that change in mariner 2 without a specific need/request.

**Comment by AZaugg** [comment]
Hey @mfrw do you have access to the build environment, or is it ephemeral? I would need access to that log file if you wanted me to dive into this further.

**Comment by mfrw** [comment]
> Hey @mfrw do you have access to the build environment, or is it ephemeral? I would need access to that log file if you wanted me to dive into this further.

I can share the logs files offline :)

**Review by mfrw — COMMENTED** [review]
A new build triggered after a rebase with main.
- [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=422988&view=results)

**Review by christopherco — APPROVED** [review]

**Pull request merged**
