### PR TITLE
Update KeysInUse-OpenSSL package to 0.3.4

### PR DESCRIPTION
**Pull request by mamckee**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

This PR updates the KeysInUse-OpenSSL package to the latest source which fixes a memory leak in high-reload public key scenarios.

###### Change Log  

- Updates KeysInUse-OpenSSL package to 0.3.4

###### Does this affect the toolchain?  

NO

###### Test Methodology

- Local build (Ubuntu VM amd64 and aarch64)

### CODE REVIEW

**Comment by mamckee** [comment]
Updated sources need to be uploaded: https://github.com/microsoft/KeysInUse-OpenSSL/releases/tag/v0.3.4

**Comment by mamckee** [comment]
@microsoft/cbl-mariner-openssl gentle ping on this. Updated sources need to be uploaded as well.

**Comment by oliviacrain** [comment]
Uploaded source, kicked off a [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=425592)

**Review by oliviacrain — APPROVED** [review]
Buddy build passes, LGTM!

**Review by dmcilvaney — APPROVED** [review]

**Pull request merged**
