### PR TITLE
Fix typo in zshrc

### PR DESCRIPTION
**Pull request by eltociear**
enviroment -> environment

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 
enviroment -> environment

###### Change Log  

- Change

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Review by PawelWMS — CHANGES_REQUESTED** [review]
Thank you for this contribution! May I ask you, however, to rebase the PR against the `1.0-dev` branch? That's where the updates for the current month are going into. We should probably update our guidelines...;)

**Comment by mfrw** [comment]
@eltociear I think, the base branch has changed to `1.0` again instead of `1.0-dev`.
Can you please change it to `1.0-dev`

**Comment by eltociear** [comment]
@PawelWMS @mfrw I'm sorry. I couldn't fix it, so I opened a new PR.
https://github.com/microsoft/CBL-Mariner/pull/1139

**Comment by mfrw** [comment]
No worries at all :)

**Pull request closed without merging**
