### PR TITLE
Move crashkernel= parameter from kernel rpm to kexec-tools rpm

### PR DESCRIPTION
**Pull request by ddstreet**
Fixes: #5460

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Move crashkernel= parameter from kernel rpm to kexec-tools rpm to solve #5460 

###### Change Log  

Move crashkernel= parameter from kernel rpm to kexec-tools rpm

###### Does this affect the toolchain?  

YES

###### Associated issues  

- #5460

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Review by dmcilvaney — APPROVED** [review]

**Review by oliviacrain — APPROVED** [review]

**Review by christopherco — CHANGES_REQUESTED** [review]
Other than the kexec-tools signature file regeneration, rest LGTM

**Review by rlmenge — APPROVED** [review]
LGTM (once signatures are updated)

**Comment by ddstreet** [comment]
Unfortunately, this isn't a very good approach due to our current image build process.

In Mariner, the `/boot/grub2/grub.cfg` file isn't actually owned by any package; it's generated by the image build tooling. This unfortunately means we have no (good) way to deliver a fix to this file for existing end users.

This prevents this PR from being mergable as it is now because, if it was, then end users who upgraded to the new kernel package would have the `crashkernel=` parameter removed from their `/boot/mariner.cfg` file, and (if they installed or upgraded to the new kexec-tools package) the `crashkernel=` parameter would be added to the new `/boot/kdump.cfg` file. However, since we have no way to update the `grub.cfg` file to include the new configuration from the `kdump.cfg` file,  their system would no longer include the `crashkernel=` parameter and they would not be able to capture any kernel crashdumps.

I don't think we can proceed with this PR until we change from our current design of generating the grub.cfg from our image build tooling over to properly using the standard `grub-mkconfig` tooling to generate the grub configuration based on the standard grub config in `/etc`. And even then, we need to carefully consider if existing users would be impacted by the change.

**Comment by dmcilvaney** [comment]
> Unfortunately, this isn't a very good approach due to our current image build process.
> 
> In Mariner, the `/boot/grub2/grub.cfg` file isn't actually owned by any package; it's generated by the image build tooling. This unfortunately means we have no (good) way to deliver a fix to this file for existing end users.
> 
> This prevents this PR from being mergable as it is now because, if it was, then end users who upgraded to the new kernel package would have the `crashkernel=` parameter removed from their `/boot/mariner.cfg` file, and (if they installed or upgraded to the new kexec-tools package) the `crashkernel=` parameter would be added to the new `/boot/kdump.cfg` file. However, since we have no way to update the `grub.cfg` file to include the new configuration from the `kdump.cfg` file, their system would no longer include the `crashkernel=` parameter and they would not be able to capture any kernel crashdumps.
> 
> I don't think we can proceed with this PR until we change from our current design of generating the grub.cfg from our image build tooling over to properly using the standard `grub-mkconfig` tooling to generate the grub configuration based on the standard grub config in `/etc`. And even then, we need to carefully consider if existing users would be impacted by the change.

Can we add some logic to kernel.cfg to check for the presence of this file as a stopgap until m3, and use today's default otherwise?

```bash
# Inside kernel.cfg
if [ -f /boot/kdump.cfg ]
    load_env -f /boot/kdump.cfg
else
    kdump_cfg="crashkernel=256M"
fi

mariner_cmdline=init=/lib/systemd/systemd ro loglevel=3 no-vmw-sta $kdump_cfg
...

```

**Comment by ddstreet** [comment]
> > Unfortunately, this isn't a very good approach due to our current image build process.
> > In Mariner, the `/boot/grub2/grub.cfg` file isn't actually owned by any package; it's generated by the image build tooling. This unfortunately means we have no (good) way to deliver a fix to this file for existing end users.
> > This prevents this PR from being mergable as it is now because, if it was, then end users who upgraded to the new kernel package would have the `crashkernel=` parameter removed from their `/boot/mariner.cfg` file, and (if they installed or upgraded to the new kexec-tools package) the `crashkernel=` parameter would be added to the new `/boot/kdump.cfg` file. However, since we have no way to update the `grub.cfg` file to include the new configuration from the `kdump.cfg` file, their system would no longer include the `crashkernel=` parameter and they would not be able to capture any kernel crashdumps.
> > I don't think we can proceed with this PR until we change from our current design of generating the grub.cfg from our image build tooling over to properly using the standard `grub-mkconfig` tooling to generate the grub configuration based on the standard grub config in `/etc`. And even then, we need to carefully consider if existing users would be impacted by the change.
> 
> Can we add some logic to kernel.cfg to check for the presence of this file as a stopgap until m3, and use today's default otherwise?
> 
> ```shell
> # Inside kernel.cfg
> if [ -f /boot/kdump.cfg ]
>     load_env -f /boot/kdump.cfg
> else
>     kdump_cfg="crashkernel=256M"
> fi
> 
> mariner_cmdline=init=/lib/systemd/systemd ro loglevel=3 no-vmw-sta $kdump_cfg
> ...
> ```

IMHO we shouldn't further hack things. We should do things right using grub-mkconfig and this PR should wait until that's done.

**Comment by ddstreetmicrosoft** [comment]
Closing this in favor of the work @Camelron has been doing to enable grub2-mkconfig and move the crashkernel= parameter to the kexec-tools package.

**Pull request closed without merging**
