### PR TITLE
Upgrade KeysInUse-OpenSSL to 0.3.3

### PR DESCRIPTION
**Pull request by mamckee**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

The KeysInUse engine was updated to prevent being loaded by applications statically linked to OpenSSL. Due to the interaction between the engine and libcrypto, engine load by statically linked applications can lead to a crash. Normally KeysInUse will only be loaded by dynamically linked applications on Mariner, via a patch to libcrypto, but the engine still should not load for statically linked applications via other means (e.g. openssl config or the dynamic engine)

###### Change Log  

- Updated KeysInUse-OpenSSL.SPEC to the latest sources, which include a fix to prevent loading by applications statically linked to OpenSSL.
- Updated signatures and cgmanifest files to reflect the new sources

###### Does this affect the toolchain?  

NO

###### Test Methodology

- Local build, tested built RPM on local Mariner 2 VM

### CODE REVIEW

**Comment by mamckee** [comment]
I will need help to upload the latest sources to the source server:
https://github.com/microsoft/KeysInUse-OpenSSL/releases/tag/v0.3.3

**Comment by oliviacrain** [comment]
> I will need help to upload the latest sources to the source server: https://github.com/microsoft/KeysInUse-OpenSSL/releases/tag/v0.3.3

Ack, doing that now, will reply here once that's done.

**Comment by oliviacrain** [comment]
> I will need help to upload the latest sources to the source server: https://github.com/microsoft/KeysInUse-OpenSSL/releases/tag/v0.3.3

File is uploaded to the [blobstore](https://cblmarinerstorage.blob.core.windows.net/sources/core/KeysInUse-OpenSSL-0.3.3.tar.gz). Name and sha256 hash match the contents of the PR. 

I kicked off a [buddy build for this PR](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=361775&view=results) as well.

**Comment by oliviacrain** [comment]
Adding @microsoft/cbl-mariner-openssl as reviewers here as well, although I'm unsure if their ownership of that area extends to engines.

**Comment by mamckee** [comment]
@oliviacrain I just pushed changes to fix aarch64 native compilation. Validated the build on aarch64 with Ubuntu 20.04. I updated the tag in the KeysInUse-OpenSSL repo for the new sources.

**Comment by oliviacrain** [comment]
[Build against the new bits looks good!](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=365907)

**Comment by mamckee** [comment]
@microsoft/cbl-mariner-openssl for review

**Comment by dmcilvaney** [comment]
@mamckee Trying to get a build out to validate with, ADO pipeline is having some hiccups today.

**Comment by dmcilvaney** [comment]
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=369642&view=results

Assuming build is green will give thumbs up.

**Review by dmcilvaney — APPROVED** [review]

**Pull request merged**
