### PR TITLE
Back ported tsflags=nodocs supported into tdnf

### PR DESCRIPTION
**Pull request by AZaugg**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

The feature to use tsflags and remove docs was added to the upstream project, backporting that feature into mariner.

This patch file had to modified to support tdnf version 3.2.2

https://github.com/vmware/tdnf/commit/cccf140befaf58d44a42f4bbcd5eeba4ddf44a06

###### Change Log  

- Change: Ported upstream patch to tdnf in mariner  add support for tsflags=nodocs

###### Does this affect the toolchain?  

NO

###### Test Methodology

- Checked out tdnf code base, went to branch 3.2.2
- Applied my patch
- Patch  applied fine
- I tried to build out all packages on Mariner via sudo make toolkit/build-packages, but having trouble getting it to build

### CODE REVIEW

**Review by rlmenge — CHANGES_REQUESTED** [review]
Please bump the release number for tdnf.spec, add a new changelog entry, and bump the toolchain manifest files to match the new release (see https://github.com/microsoft/CBL-Mariner/commit/1c234d6df958d12a81110fba3bb6a18f6c979850#diff-ebcd47dd20b5f3db26f6d276c0709163ecff58c254933b045f4e30f86e9071d0 for reference)

**Review by PawelWMS — COMMENTED** [review]
Thank you for adding the change! I think we're now just down to updating the manifest already mentioned by @rlmenge.

**Comment by AZaugg** [comment]
OK, bumped the mainifest files

**Review by PawelWMS — APPROVED** [review]
Looks good to me. Not sure why the PR checks got stuck. Pushing a dummy commit might help.

**Review by rlmenge — APPROVED** [review]

**Pull request merged**
