### PR TITLE
Enable CONFIG_ARM_SMMU and CONFIG_ARM_SMMU_V3 in aarch64.

### PR DESCRIPTION
**Pull request by ddaney-fungible**
Set CONFIG_ARM_SMMU_DISABLE_BYPASS_BY_DEFAULT for aarch64 kernel as it is the more secure setting.

Adjust mariner-required-configs.json for aarch64 kernel IOMMU configs.

Update all spec Release strings to match kernel.spec

Update manifests to match kernel-headers version.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Enable IOMMU in aarch64 kernel. It is needed to allow VFIO to be used with Mariner.

###### Change Log  

- Enable CONFIG_ARM_SMMU and CONFIG_ARM_SMMU_V3 in aarch64 kernel.

###### Does this affect the toolchain?  

NO

###### Associated issues  

- #6818

###### Test Methodology

- local build on 2.0 branch

### CODE REVIEW

**Comment by ddaney-fungible** [comment]
This is just a rebase of my 2.0 branch PR here: https://github.com/microsoft/CBL-Mariner/pull/6823

The kernel package built in the 2.0 branch version, but I haven't yet figured out the proper incantation for a main branch build as a bunch of toolchain RPMs don't exist and cannot be downloaded.

**Comment by rlmenge** [comment]
> This is just a rebase of my 2.0 branch PR here: #6823
> 
> The kernel package built in the 2.0 branch version, but I haven't yet figured out the proper incantation for a main branch build as a bunch of toolchain RPMs don't exist and cannot be downloaded.

main is our development branch. As such, some of the packages may not yet be published. This is why you are seeing download failures. To build on the main branch, use the quickrebuild commands to build the toolchain and packages

```
sudo make toolchain QUICK_REBUILD_TOOLCHAIN=y CONFIG_FILE=""
sudo make build-packages REBUILD_TOOLS=y CONFIG_FILE= PACKAGE_REBUILD_LIST="kernel"
```

**Comment by christopherco** [comment]
Thanks @rlmenge for kicking off the buddy builds. Looks to build clean - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=457103&view=results

**Review by christopherco — APPROVED** [review]

**Comment by christopherco** [comment]
LGTM @ddaney-fungible - Thanks for the contribution!

**Pull request merged**
