### PR TITLE
Removing tarballs from the repository.

### PR DESCRIPTION
**Pull request by PawelWMS**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

Looks like accidentally we checked-in some compressed sources into our repo. Removing them now, they are available in the blob storage.

###### Change Log  

- Removed a bunch of archives from the repo.

###### Does this affect the toolchain?  

No.

###### Test Methodology

- Checked that the removed tarballs are available in our blob storage.

### CODE REVIEW

**Review by rlmenge — APPROVED** [review]

**Review by jslobodzian — APPROVED** [review]
Woah...glad you are removing these.

**Comment by dmcilvaney** [comment]
I'm surprised these got in, we have `SPECS/**/*.bz2` etc... in our `.gitignore`. Might be worth double checking that is working as intended.

**Review by dmcilvaney — APPROVED** [review]

**Comment by dmcilvaney** [comment]
Maybe room for a GitHub action to flag these at PR?

**Comment by PawelWMS** [comment]
> I'm surprised these got in, we have `SPECS/**/*.bz2` etc... in our `.gitignore`. Might be worth double checking that is working as intended.

I read this too late, but that's a very good idea. I just checked what we ignore and it seems like we are limiting ourselves to the `SPECS` folder only. I'm going to fix that in a separate PR in a few minutes. Thanks!

**Pull request merged**
