### PR TITLE
Revert "Added a toolkit check for required tooling. (#6199)"

### PR DESCRIPTION
**Pull request by mfrw**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This reverts commit d3fd41653a532e9f9f3a871c49786982ed904223.
This seems to be breaking in the pipeline.
/cc @anphel31

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #6199

###### Links to CVEs  
- NA

###### Test Methodology

- NA
Trigger a Buddy build by rebasing a failing PR with this change. [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=423605&view=results)

### CODE REVIEW

**Comment by anphel31** [comment]
Thanks Falak. This revert will fix the following error seen in pipelines:
`/mnt/vss/_work/1/s/CBL-Mariner/toolkit/scripts/tools.mk:221: *** "Tool 'awk' missing! Please install it before using the toolkit.".  Stop.`

**Review by anphel31 — APPROVED** [review]

**Comment by dmcilvaney** [comment]
Switching it to the original implementation using `which` seems to still work:
```make
$(foreach exec,awk curl docker git go setfacl tar wget foobar, \
	$(if $(call shell_real_build_only,which $(exec)),,$(error "Tool '$(exec)' missing! Please install it before using the toolkit.")) \
)
```

**Comment by mfrw** [comment]
> Switching it to the original implementation using `which` seems to still work:
> 
> ```makefile
> $(foreach exec,awk curl docker git go setfacl tar wget foobar, \
> 	$(if $(call shell_real_build_only,which $(exec)),,$(error "Tool '$(exec)' missing! Please install it before using the toolkit.")) \
> )
> ```
> 
> I can't make heads or tails of why this doesn't work though... testing via `sudo make printvar-SHELL`: `sudo make printvar-SHELL` -> `make: command: Command not found` `sudo make printvar-SHELL SHELL=sh` -> Works fine `sudo make printvar-SHELL SHELL=bash` -> Works fine `sudo make printvar-SHELL SHELL=/bin/sh` -> `make: command: Command not found`
> 
> Ok, so I know sometimes Ubuntu symlinks `sh` to different things, and the default value for `SHELL` is `/bin/sh... so `which sh`->`/bin/sh`... what?
> 
> When I use `SHELL=sh` it works... but `SHELL=/bin/sh` fails... but bash tells me they are the same thing...

Ubuntu sometimes links /bin/sh -> /bin/dash

**Comment by dmcilvaney** [comment]
> > Switching it to the original implementation using `which` seems to still work:
> > ```makefile
> > $(foreach exec,awk curl docker git go setfacl tar wget foobar, \
> > 	$(if $(call shell_real_build_only,which $(exec)),,$(error "Tool '$(exec)' missing! Please install it before using the toolkit.")) \
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can't make heads or tails of why this doesn't work though... testing via `sudo make printvar-SHELL`: `sudo make printvar-SHELL` -> `make: command: Command not found` `sudo make printvar-SHELL SHELL=sh` -> Works fine `sudo make printvar-SHELL SHELL=bash` -> Works fine `sudo make printvar-SHELL SHELL=/bin/sh` -> `make: command: Command not found`
> > Ok, so I know sometimes Ubuntu symlinks `sh` to different things, and the default value for `SHELL` is `/bin/sh... so `which sh`->`/bin/sh`... what?
> > When I use `SHELL=sh` it works... but `SHELL=/bin/sh` fails... but bash tells me they are the same thing...
> 
> Ubuntu sometimes links /bin/sh -> /bin/dash

That is the underlying terminal, yes. But interestingly setting `SHELL=dash` works fine, as does `SHELL=/bin/dash`.

Only `SHELL=/bin/sh` fails.

**Pull request merged**
