### PR TITLE
imagegen: disktutils: Fix parted/partprobe error code.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

I tried to build CBL Mariner 2.0 ISO on top of 455142ea03c1 because I want to test something related to BTF and kernel BTF related `CONFIG_*` were added in 2.0.
I was successful to build the ISO but it sadly failed when trying to install it on a virtual disk within `qemu`.
The errors were related to `parted` and `partprobe` which return code `!= 0` while actually doing what they should do (you can find more information about it in the source code).

I agree this PR does not address the root cause of the problem but I had to be a pragmatic about it.
I mainly opened it to inform you about this problem and share a temporary solution to other people which could face it.

If you see any way to improve this PR, feel free to share it.

###### Change Log  
- Modify `diskutils.go` to check if `parted` and `partprobe` actually did what they are supposed while not relying only on their return code.

###### Does this affect the toolchain?  
The toolchain was **not** modified.

###### Test Methodology
I tested this PR installing succesfully a CBL Mariner 2.0 with qemu and running it:
image

Best regards.

### CODE REVIEW

**Comment by MaxBrodeurUrbas** [comment]
This bug was introduced when upgrading parted to v3.4. That upgrade has since been reverted. I believe the underlying parted issue is addressed with this [modification](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=1af57544e419afdbc54cb6dc76e053593e4bb088) from [this thread ](https://bugs.gentoo.org/704704) Testing this fix out now with parted 3.4

**Comment by eiffel-fl** [comment]
Hi.

Thank you for your reply.
I am not really sure the issue you linked addressed this problem since the mentioned fix seems to be about atari labels and mariner does not use such partition type.

Can you please indicate me on top of which commit should I rebase to be OK regarding this problem?
And also, where can I find the rpms.tar.gz corresponding to this commit? I would like to avoid rebuilding all the packages if possible.

Best regards and thank you in advance.

**Review by mfrw — COMMENTED** [review]
@eiffel-fl thank you for your contribution. We generally raise a PR against the `main` branch instead of `2.0`.
Can you please change your base to `main`

**Comment by eiffel-fl** [comment]
Hi.

I changed the based branch from 2.0 to main.
Sadly, I did not test this change against main, I will do it and come back later with confirmation it works or modification to ensure it works.

Best regards.

**Comment by MaxBrodeurUrbas** [comment]
> Hi.
> 
> Thank you for your reply. I am not really sure the issue you linked addressed this problem since the mentioned fix seems to be about atari labels and mariner does not use such partition type.
> 
> Can you please indicate me on top of which commit should I rebase to be OK regarding this problem? And also, where can I find the rpms.tar.gz corresponding to this commit? I would like to avoid rebuilding all the packages if possible.
> 
> Best regards and thank you in advance.

Hi! sorry for the late reply here. I believe you're right, tested out the patch and iso issue persists. I will keep looking into it. In terms of the upgrade reversion, [here](https://github.com/microsoft/CBL-Mariner/commit/4a373bbc9b5ce847d6b10d52a39f1065bd393a31) is the commit and [here ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=161950&view=results) is the link to the internal pipeline artifcats to grab the rpms.tar.gz.

**Comment by eiffel-fl** [comment]
Hi.

No problem, I understand.
Regarding the patch I sent, this is clearly not the best solution and I sent to help someone who would be in the same situation than me.
I think the good way would be to bump parted version (or a patch to it) to fix this strange behavior but this is quite easy to say and more complicated to actually fix it.

Anyway, I think I will wait until stable 2.0 is released to continue my tests.
During this time, if you need some help you can ping me.

Best regards.

**Comment by christopherco** [comment]
Just closing the loop on this - @MaxBrodeurUrbas identified the root cause and applied a patch as part of a new version upgrade to parted v3.4. https://github.com/microsoft/CBL-Mariner/pull/2133

**Comment by eiffel-fl** [comment]
Perfect! I also did not have this bug when I tested on `2.0-stable`.

**Pull request closed without merging**
