### PR TITLE
Initial spec lint action commit

### PR DESCRIPTION
**Pull request by thcrain-msft**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

Adds a GitHub Action which uses a custom version of openSUSE's [spec-cleaner](https://github.com/rpm-software-management/spec-cleaner) to ensure properly formatted and correct *.spec files.

###### Change Log  
- Add spec-lint.yml workflow as a check for pushes and PRs targeting main/dev/1.0* branches which affect *.spec files
- Add Mariner-specific patch file for spec-cleaner
- Linter will output formatted versions of spec files to the artifact for the action
- Document detailing what is being checked by the tool are being reviewed internally

###### Does this affect the toolchain?  

**NO**

### CODE REVIEW

**Review by jslobodzian — APPROVED** [review]

**Comment by PawelWMS** [comment]
> deleted file mode 100644

This is a bit lengthy to read. Is there a sample spec to look at, which would show what rules we're going to follow for the specs?

---
Refers to: .github/workflows/mariner-spec-cleaner.patch:2 in 788ded0. [](commit_id = 788ded08b0e27f3de42c8c67dcd6ddb09c3d5c2d, deletion_comment = False)

**Review by dmcilvaney — APPROVED** [review]
Agree with Pawel that the patch is a bit hefty to review. At a high level what changes were made to it? Curious where we diverge from SUSE.

The workflow itself looks good though.

**Comment by thcrain-msft** [comment]
Hi @PawelWMS @dmcilvaney,

Sorry- didn't leaving a comment saying that the patch itself is not meant to be reviewed! Agree that it would be hefty to review on its own 😃  The source of the tool can be found in the "fork" branch of the `spec-cleaner-fork` repo in ADO. You can view a high level list of expectations for spec files on the internal wiki- the page is named "Spec File Best Practices".

**Comment by thcrain-msft** [comment]
Clarifying: this is going into the main branch, as we have a requirement that the spec-cleaner patch is pulled from there. This PR will be cherry-picked into dev and 1.0-dev after this is merged.

**Pull request merged**
