### PR TITLE
toolkit: containerized-build: add vim & git in the build env

### PR DESCRIPTION
**Pull request by mfrw**
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
To help improve the developer expeirience w.r.t to the `containerized-build` feature,
add a minimal set of tools, so that we dont have to install them everytime we start.

###### Change Log  

- Add `git` & `vim` to build container

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- NA

###### Links to CVEs  
- NA

###### Test Methodology

- Local build and test

### CODE REVIEW

**Review by ameyapu — APPROVED** [review]
LGTM.  I find this very useful and would suggest that we keep observing if there are other small tools too that can be added.

**Review by neha170 — APPROVED** [review]
My only concern with adding packages to the container is that it should not alter behaviour when building packages. The aim is to keep the container as close to the build chroot as possible. When adding packages, the user should be aware that they have installed packages which are not present in typical build chroot (and their effect). These packages (vim, git) look harmless to add. Thoughts @dmcilvaney?

**Comment by dmcilvaney** [comment]
> My only concern with adding packages to the container is that it should not alter behaviour when building packages. The aim is to keep the container as close to the build chroot as possible. When adding packages, the user should be aware that they have installed packages which are not present in typical build chroot (and their effect). These packages (vim, git) look harmless to add. Thoughts @dmcilvaney?

I'm not opposed, but agreed that every change is a trade-off. Each additional .rpm in the build environment will change the behavior of `autoconf` etc. which can result in the built packages having different dependencies/libraries etc than the "real" versions.

My personal workflow for this is to mount the interesting directories out of the container and use my normal editor/tools on them from outside (vscode in this case).

**Comment by mfrw** [comment]
> > My only concern with adding packages to the container is that it should not alter behaviour when building packages. The aim is to keep the container as close to the build chroot as possible. When adding packages, the user should be aware that they have installed packages which are not present in typical build chroot (and their effect). These packages (vim, git) look harmless to add. Thoughts @dmcilvaney?
> 
> I'm not opposed, but agreed that every change is a trade-off. Each additional .rpm in the build environment will change the behavior of `autoconf` etc. which can result in the built packages having different dependencies/libraries etc than the "real" versions.
> 
> My personal workflow for this is to mount the interesting directories out of the container and use my normal editor/tools on them from outside (vscode in this case).

Given this is a `DevEx` feature, aimed at making `our` lives better [IMO].
We might as well, reduce a little bit of repetition. I will probably merge it.
If it causes issues latter-on, we can drop it :)

**Pull request merged**
