### PR TITLE
[dev] Prune unnecessary toolchain packages

### PR DESCRIPTION
**Pull request by thcrain-msft**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

We have a fair number of packages in the toolchain. Toolchain packages should be a base set of packages needed to bootstrap a package building environment along with the packages needed to build them. After the recent removal of certain packages (`audit`, `openldap`, `tcp_wrappers`, `cryptsetup`, `lvm2`) from the toolchain, we no longer need several of their dependencies to be in the toolchain.

###### Change Log  

- Remove `golang` from the toolchain- not needed after previous removal of `audit`
- Remove `libcap-ng` from the toolchain- not needed after previous removal of `audit`
- Remove `groff` from the toolchain- not needed after previous removal of `openldap`
- Remove `perl-File-HomeDir` from the toolchain- not needed after removal of `groff`
- Remove `perl-File-Which` from the toolchain- not needed after removal of `perl-File-HomeDir`
- Remove `libnsl2` from the toolchain- not needed after previous removal of `tcp_wrappers`
- Remove `libtirpc` from the toolchain- not needed after removal of `libnsl2`
- Remove `rpcsvc-proto` from the toolchain- not needed after removal of `libnsl2`
- Remove `libpwquality` from the toolchain- not needed after previous removal of `cryptsetup`
- Remove `json-c` from the toolchain- not needed after previous removal of `cryptsetup`
- Remove `libaio` from the toolchain- not needed after previous removal of `lvm2`
- Remove several perl packages that are part of the `groff` dependency chain
- Move `krb5` install to before `curl` build
- Move `intltool` install to before `systemd-bootstrap` build
- Remove double installs of `gperf`, `libselinux`, `libsepol`

###### Does this affect the toolchain?  

**YES**

###### Test Methodology

- Full local package build to ensure packages aren't relying implicitly on removed worker chroot packages

### CODE REVIEW

**Review by PawelWMS — COMMENTED** [review]
I love the changes. Have you also ran an end-to-end pipeline build to double-check we're not breaking anywhere?

**Review by PawelWMS — COMMENTED** [review]
Have you checked, if the removed packages are still needed in the following scripts and files (I think they are related to building the 1<sup>st</sup> stage toolchain):
- `toolchain_build_in_chroot.sh`,
- `toolchain_build_temp_tools.sh`,
- `toolchain-sha256sums`, and
- `toolchain-remote-wget-list`?

**Review by nicogbg — APPROVED** [review]

**Comment by thcrain-msft** [comment]
> I love the changes. Have you also ran an end-to-end pipeline build to double-check we're not breaking anywhere?

I have- the build didn't pass, but the only failures were the unrelated known failures in the dev branch.

**Comment by thcrain-msft** [comment]
> Have you checked, if the removed packages are still needed in the following scripts and files (I think they are related to building the 1st stage toolchain):
> 
> * `toolchain_build_in_chroot.sh`,
> * `toolchain_build_temp_tools.sh`,
> * `toolchain-sha256sums`, and
> * `toolchain-remote-wget-list`?

The only one I'm unsure about is `libcap-ng`. I'll be putting that on my plate later to remove from the raw toolchain, since it's not explicitly used in the LFS book. I talked at length with Jon about having packages in the raw toolchain but not produced as RPMs, and we agreed it's something we're willing to do to avoid toolchain bloat.

**Pull request merged**
