### PR TITLE
Disable kernel config SLUB_DEBUG_ON due to tcp throughput perf impact

### PR DESCRIPTION
**Pull request by chalamalasetty**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Enabling CONFIG_SLUB_DEBUG_ON have a perf impact with tcp throughput. Hence disabling it

###### Change Log  

Disable kernel config SLUB_DEBUG_ON due to tcp throughput perf impact

###### Does this affect the toolchain?  

YES
**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/...

###### Test Methodology

-Built kernel by disabling CONFIG_SLUB_DEBUG_ON and verified.

### CODE REVIEW

**Review by nicogbg — APPROVED** [review]

**Review by christopherco — CHANGES_REQUESTED** [review]
`CONFIG_SLUB_DEBUG_ON` is a recommended kernel hardening config. Given the perf hit, we should try disabling `CONFIG_SLUB_DEBUG_ON` and pass `slub_debug=ZF` on the kernel command line to retain the important hardening components.

**Comment by chalamalasetty** [comment]
Verified with  slub_debug=ZF  flag and seeing nearly 50% of perf impact with tcp throughput.

**Review by christopherco — APPROVED** [review]
:shipit:

**Comment by christopherco** [comment]
Discussed offline a bit. Will take this change now and consider how best to enable `slub_debug=ZF` in a future PR.

**Pull request merged**
